# Generated by Django 4.0.4 on 2022-05-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_questionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name_plural': 'QuestionModel'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
