# Generated by Django 4.0.1 on 2022-05-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_alter_quizcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='image',
            field=models.ImageField(upload_to='category_image/'),
        ),
    ]
