# Generated by Django 4.0.4 on 2022-05-07 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0007_alter_quizcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Performace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_que', models.PositiveIntegerField()),
                ('attempt_que', models.PositiveIntegerField()),
                ('points', models.PositiveBigIntegerField()),
                ('true_que', models.PositiveIntegerField()),
                ('wrong_que', models.PositiveIntegerField()),
                ('result', models.BooleanField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('quize_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizcategory', to_field='title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
