# Generated by Django 4.0.4 on 2022-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_alter_quizcategory_title_performace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='point',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
